### ISSUE TITLE
Schema akzeptiert <head> in <div> nicht

### ISSUE THREAD

**Issue by peertrilcke** [DLiNa/project#6]
Hei in die Runde, 

wie sich gerade in einer Korrespondenz mit Christof Schöch rausstellt, scheint unser RNC-Schema (?) unsere linas für ungültig zu erklären: head in div scheint nicht erlaubt, unsere linas sind aber voller heads in divs. Was ist das passiert? Das war ja früher nicht so? Bestes

**Comment by mathias-goebel** [comment]
https://github.com/dlina/project/blob/master/rules/lina.rnc#L57
Zeile 57 und 58 deute ich so, dass in `div` 0 oder mehr von `div` oder `head` erlaubt sind.
@christofs Wie und/oder womit wurde getestet?

**Comment by peertrilcke** [comment]
also ich habe das hier getestet (mit Oxygen): 
https://raw.githubusercontent.com/dlina/project/master/data/zwischenformat/1731-Gottsched_Johann_Christoph-Der_sterbende_Cato-lina.xml

Christof hat, soweit ich sehe, mit einer eigenen lina (noch in der Entwicklung, siehe zip der xml hier: https://github.com/dlina/project/files/446861/tc0611_ZF.xml.zip) gegen das hier getestet:
https://github.com/dlina/project/blob/master/rules/lina.rnc

**Comment by dariok** [comment]
@peertrilcke Bitte einmal mit dem Schema aus dem Branch schema-test probieren:
https://raw.githubusercontent.com/dlina/project/06130a8dd2f5d8ac4a5aca7d611b08450063e337/rules/lina.rnc

**Comment by peertrilcke** [comment]
mit dem schema funktioniert es sowohl mit unserer lina.xml (die oben verlinkte) als auch mit der von Christof

**Comment by peertrilcke** [comment]
Zeile 2 und 3 in den lina sehen bei mir jetzt also so aus 
<?xml-model href="https://raw.githubusercontent.com/dlina/project/06130a8dd2f5d8ac4a5aca7d611b08450063e337/rules/lina.rnc"?>
<?xml-model href="https://raw.githubusercontent.com/DLiNa/project/master/rules/lina.sch"?>

Das bei lina.sch auf einen anderen Ort als bei lina.rnc verwiesen wird, ist richtig?

**Comment by peertrilcke** [comment]
bitte zum comment close noch mal die korrekten links zu den beiden Dateien posten

zwei weitere issues (würde ich eröffnen) wären dann noch: 
- in unseren linas müssten die Links zu den Schemata geändert werden
- bei Christof meckert unserer Schema immer noch, und zwar wegen der id im play-tag, Christof hat dort "0611tc" stehen, worauf unser Schema sagt "must be an inetger"; muss es das denn unbedingt sein, könnte man da nicht weniger restriktiv auch andere ID-Modelle zulassen?
  Grüße

**Comment by dariok** [comment]
Die xml-model-Zeilen müssen nicht verändert werden. Da die Änderungen funktionieren habe ich sie in Master eingepflegt.

**Comment by christofs** [comment]
Sorry, dass ich da mit dem Schema so einen Sturm im Wasserglas ausgelöst habe. Bin nicht sicher, warum ich da soviele Fehlermeldungen von Oxygen bekommen hatte. Habe jetzt mit altem und neuem Schema getestet und es sieht viel besser aus. Selbst meine @type und @n in den "div"s sind ok. Dass diese @id in "play" ein Integer sein muss, finde ich auch etwas restriktiv, oder ist das XML-Manier? Mein Wunschmodell wäre im Übrigen "\w\w\d\d\d\d" (bspw. "tc1234") bzw, eines, das sowas erlaubt, weil so alle unsere CLiGS-IDs aussehen.
