### ISSUE TITLE
Provide .rng as well as .rnc?

### ISSUE THREAD

**Issue by christofs** [DLiNa/project#8]
Just an enhancement suggestion. It would be useful to have .rng as well because lxml cannot read .rnc files directly. Validation as part of a workflow generating "Zwischenformat" and involving lxml would become much easier.

**Comment by dariok** [comment]
@christofs Bitte testen

**Comment by christofs** [comment]
Funktioniert (mit Oxygen; in lxml muss ich das erst einbauen, jetzt wo es möglich ist). Danke!

**Comment by dariok** [comment]
Immer gerne :)
